name: Deploy to Firebase

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install frontend dependencies
        run: bun install

      - name: Install functions dependencies
        run: |
          cd functions
          npm install
          cd ..

      - name: Create serviceAccount.env.json & .env files
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_COFFEZ_CH }}' > ./functions/serviceAccount.env.json
          echo 'FIREBASE_ADMIN_KEY=${{ secrets.FIREBASE_SERVICE_ACCOUNT_COFFEZ_CH }}' > ./.env
          echo 'FIREBASE_FRONTEND_KEY=${{ secrets.FIREBASE_FRONTEND_APIKEY }}' > ./.env

      - name: Create .env file in functions
        run: |
          echo "SLACK_TOKEN=${{ secrets.SLACK_TOKEN }}" > ./functions/.env
          echo "POSTMARK_TOKEN=${{ secrets.POSTMARK_TOKEN }}" >> ./functions/.env
          echo "SLACK_COMMANDES=${{ secrets.SLACK_COMMANDES }}" >> ./functions/.env
          echo "COMPANY_ADDRESS=${{ secrets.COMPANY_ADDRESS }}" >> ./functions/.env
          echo "EMAIL_FROM=${{ secrets.EMAIL_FROM }}" >> ./functions/.env

      - name: Build frontend
        run: bun run build

      - name: Build functions
        run: bun run functions

      - name: Deploy to firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_COFFEZ_CH }}
          channelId: live
          projectId: coffez-ch

      - name: Deploy functions
        run: bun run firebase-deploy --only-functions
