name: Deploy to Firebase

on:
  push:
    branches:
      - feature/enable-github-ci

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      COMPANY_ADDRESS: ${{ secrets.COMPANY_ADDRESS }}
      EMAIL_FROM: ${{ ${{ secrets.EMAIL_FROM }} }}
      SLACK_COMMANDES: ${{ secrets.SLACK_COMMANDES }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      POSTMARK_TOKEN: ${{ secrets.POSTMARK_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash

      - name: Install dependencies
        run: bun install

      - name: Set up Firebase CLI
        uses: w9jds/firebase-action@v2.2.1
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Run deployment script
        run: bun run deploy
